/**
 * k6 Load Test — File Upload
 *
 * Simulates file upload scenarios:
 * - Upload small text/CSV files
 * - Upload larger binary files (simulated)
 * - Upload with metadata fields
 * - List uploaded files
 * - Delete uploaded file
 *
 * Uses JWT auth token from env variable.
 */

import { check, sleep, group } from "k6";
import http from "k6/http";
import { BASE_URL, BASE_OPTIONS, authParams } from "./k6-options.js";

export const options = {
  ...BASE_OPTIONS,
  thresholds: {
    ...BASE_OPTIONS.thresholds,
    "http_req_duration{name:upload_small}": ["p(95)<3000"],
    "http_req_duration{name:upload_large}": ["p(95)<8000"],
    "http_req_duration{name:list_files}":  ["p(95)<1000"],
  },
  stages: [
    { duration: "5s",  target: 5 },
    { duration: "20s", target: 20 },
    { duration: "5s",  target: 0 },
  ],
};

const AUTH_TOKEN = __ENV.AUTH_TOKEN || "";

export default function () {
  const params = AUTH_TOKEN ? authParams(AUTH_TOKEN) : {};
  let uploadedFileId = "";

  // 1. Upload small text file
  group("Upload: small file", () => {
    const fileName = `k6-test-${__VU}-${Date.now()}.txt`;
    const fileContent = `Load test file generated by k6 VU ${__VU}\nTimestamp: ${Date.now()}\nData: ${"x".repeat(1024)}`;

    const uploadBody = {
      file: http.file(fileContent, fileName, "text/plain"),
      description: `k6 upload test (VU ${__VU})`,
      tags: "loadtest,automated",
    };

    const uploadRes = http.post(
      `${BASE_URL}/api/upload`,
      uploadBody,
      { tags: { name: "upload_small" }, ...params },
    );
    check(uploadRes, {
      "upload status 200/201": (r) => r.status === 200 || r.status === 201,
      "upload has file ID": (r) => JSON.parse(r.body).id !== undefined,
    });
    uploadedFileId = JSON.parse(uploadRes.body).id;
  });

  // 2. Upload larger binary (simulated 100KB file)
  group("Upload: large file", () => {
    const fileName = `k6-large-${__VU}-${Date.now()}.dat`;
    const fileContent = "x".repeat(100 * 1024); // ~100KB

    const uploadBody = {
      file: http.file(fileContent, fileName, "application/octet-stream"),
      description: "large file load test",
    };

    const uploadRes = http.post(
      `${BASE_URL}/api/upload`,
      uploadBody,
      { tags: { name: "upload_large" }, ...params },
    );
    check(uploadRes, {
      "large upload status 200/201": (r) => r.status === 200 || r.status === 201,
    });
  });

  // 3. List uploaded files
  group("Upload: list files", () => {
    const listRes = http.get(
      `${BASE_URL}/api/upload?limit=10`,
      params,
    );
    check(listRes, {
      "list files status 200": (r) => r.status === 200,
    });
  });

  // 4. Delete uploaded file
  if (uploadedFileId) {
    group("Upload: delete file", () => {
      const deleteRes = http.del(
        `${BASE_URL}/api/upload/${uploadedFileId}`,
        null,
        params,
      );
      check(deleteRes, {
        "delete file status 200/204": (r) => r.status === 200 || r.status === 204,
      });
    });
  }

  sleep(1);
}
