/**
 * Native / Polyglot Modules — Nim stub generator (2.1)
 *
 * Generates a Nim shared-library module from a manifest:
 *   - `native/lib.nim` — `exportc` FFI entry + JSON dispatcher
 *
 * Nim ships std/json, so no embedded parser is needed. The dispatcher
 * reads `{ "fn": ..., "args": {...} }`, calls the user function, and
 * returns a JSON response.
 *
 * Build: `nim c -d:release --app:lib -o target/release/lib<name>.<ext> lib.nim`
 *
 * The user edits ONLY the function bodies (marked `# TODO: implement`).
 */

import type { NativeManifest, NativeTypeName } from "./manifest";

/** Nim type for a boundary type. */
export function nimTypeName(t: NativeTypeName): string {
  switch (t) {
    case "string":
      return "string";
    case "number":
      return "float64";
    case "boolean":
      return "bool";
    case "bytes":
      return "seq[byte]";
    case "json":
      return "JsonNode";
  }
}

/** Build a `let x = ...` extractor for one param (4-space indent, inside an if-arm). */
function nimParamExtract(
  paramName: string,
  type: NativeTypeName,
  fnName: string,
): string {
  const indent = "    ";
  switch (type) {
    case "string":
      return `${indent}let ${paramName} = if args.hasKey("${paramName}"):\n${indent}    (if args["${paramName}"].kind == JString: args["${paramName}"].getStr() else: return err("[${fnName}] param \\"${paramName}\\": expected string"))\n${indent}  else:\n${indent}    return err("[${fnName}] param \\"${paramName}\\": missing")`;
    case "number":
      return `${indent}let ${paramName} = if args.hasKey("${paramName}"):\n${indent}    (if args["${paramName}"].kind in {JInt, JFloat}: args["${paramName}"].getFloat() else: return err("[${fnName}] param \\"${paramName}\\": expected number"))\n${indent}  else:\n${indent}    return err("[${fnName}] param \\"${paramName}\\": missing")`;
    case "boolean":
      return `${indent}let ${paramName} = if args.hasKey("${paramName}"):\n${indent}    (if args["${paramName}"].kind == JBool: args["${paramName}"].getBool() else: return err("[${fnName}] param \\"${paramName}\\": expected boolean"))\n${indent}  else:\n${indent}    return err("[${fnName}] param \\"${paramName}\\": missing")`;
    case "bytes":
      return `${indent}let ${paramName} = if args.hasKey("${paramName}"):\n${indent}    try:\n${indent}      var bseq: seq[byte] = @[]\n${indent}      for item in args["${paramName}"]:\n${indent}        bseq.add(byte(item.getInt()))\n${indent}      bseq\n${indent}    except: return err("[${fnName}] param \\"${paramName}\\": expected byte array")\n${indent}  else:\n${indent}    return err("[${fnName}] param \\"${paramName}\\": missing")`;
    case "json":
      return `${indent}let ${paramName} = if args.hasKey("${paramName}"): args["${paramName}"] else: newJNull()`;
  }
}

/** Nim expression to wrap a return value into a JsonNode. */
function nimReturnExpr(expr: string, type: NativeTypeName): string {
  switch (type) {
    case "string":
      return `%*(${expr})`;
    case "number":
      return `%*(${expr})`; // float64 → JSON number
    case "boolean":
      return `%*(${expr})`;
    case "bytes":
      return `%*(${expr})`; // seq[byte] → JSON array of ints
    case "json":
      return `${expr}`;
  }
}

/** Dispatch arm for one function. */
function nimDispatchCase(manifest: NativeManifest, fnName: string): string {
  const fn = manifest.functions.find((f) => f.name === fnName);
  if (!fn) return "";
  const extracts = Object.keys(fn.params)
    .map((p) => nimParamExtract(p, fn.params[p]!, fnName))
    .join("\n");
  const callArgs = Object.keys(fn.params).join(", ");
  return `  if fnName == "${fnName}":
${extracts}
    let ret = ${fnName}(${callArgs})
    return ok(${nimReturnExpr("ret", fn.returns)})`;
}

/** Generate lib.nim with stubs + dispatcher. */
export function generateNimLib(manifest: NativeManifest): string {
  const lines: string[] = [];
  lines.push(`# Auto-generated by AsiJS — DO NOT EDIT the FFI section below.`);
  lines.push(`# Your code: fill in the bodies of the functions marked with TODO.`);
  lines.push(`# Re-run "asi native scaffold ${manifest.lang}" to regenerate the FFI glue.`);
  lines.push(`import std/json`);
  lines.push(`import std/math`);
  lines.push(``);
  lines.push(`{.push exportc, cdecl, dynlib.}`);
  lines.push(``);
  lines.push(`# ====================================================================`);
  lines.push(`# Your functions — edit the bodies below (signatures are generated)`);
  lines.push(`# ====================================================================`);
  lines.push(``);

  for (const fn of manifest.functions) {
    const params = Object.entries(fn.params)
      .map(([name, type]) => `${name}: ${nimTypeName(type)}`)
      .join(", ");
    lines.push(`proc ${fn.name}(${params}): ${nimTypeName(fn.returns)} =`);
    lines.push(`  # TODO: implement the body of ${fn.name}`);
    switch (fn.returns) {
      case "string":
        lines.push(`  return ""`);
        break;
      case "number":
        lines.push(`  return 0.0`);
        break;
      case "boolean":
        lines.push(`  return false`);
        break;
      case "bytes":
        lines.push(`  return @[]`);
        break;
      case "json":
        lines.push(`  return newJNull()`);
        break;
    }
    lines.push(``);
  }

  lines.push(`# ====================================================================`);
  lines.push(`# FFI boundary — DO NOT EDIT`);
  lines.push(`# ====================================================================`);
  lines.push(`proc ok(res: JsonNode): JsonNode =`);
  lines.push(`  result = %*{"ok": true, "result": res}`);
  lines.push(``);
  lines.push(`proc err(msg: string): JsonNode =`);
  lines.push(`  %*{"ok": false, "error": msg}`);
  lines.push(``);
  lines.push(`proc dispatch(fnName: string, args: JsonNode): JsonNode =`);
  for (const fn of manifest.functions) {
    lines.push(nimDispatchCase(manifest, fn.name));
  }
  lines.push(`  return err("unknown native function: " & fnName)`);
  lines.push(``);
  lines.push(`proc asijs_call(input: cstring): cstring {.exportc.} =`);
  lines.push(`  try:`);
  lines.push(`    let req = parseJson($input)`);
  lines.push(`    let fnName = req["fn"].getStr()`);
  lines.push(`    let args = if req.hasKey("args"): req["args"] else: newJObject()`);
  lines.push(`    let resp = dispatch(fnName, args)`);
  lines.push(`    let respStr = $resp`);
  lines.push(`    result = cast[cstring](alloc0(respStr.len + 1))`);
  lines.push(`    copyMem(result, cstring(respStr), respStr.len)`);
  lines.push(`  except CatchableError:`);
  lines.push(`    let msg = "{\\"ok\\":false,\\"error\\":\\"invalid JSON\\"}"`);
  lines.push(`    result = cast[cstring](alloc0(msg.len + 1))`);
  lines.push(`    copyMem(result, cstring(msg), msg.len)`);
  lines.push(``);
  lines.push(`proc asijs_free(p: pointer) {.exportc.} =`);
  lines.push(`  if p != nil:`);
  lines.push(`    dealloc(p)`);
  lines.push(``);
  lines.push(`{.pop.}`);
  lines.push(``);

  return lines.join("\n");
}
