/**
 * Native / Polyglot Modules — Rust stub generator (1.2)
 *
 * Generates a complete Rust cdylib crate from a manifest:
 *   - `native/Cargo.toml` — cdylib + serde/serde_json deps
 *   - `native/src/lib.rs` — `#[unsafe(no_mangle)]` FFI entry + JSON dispatcher
 *
 * The user edits ONLY the function bodies (marked with `// TODO: implement`).
 * Everything else — the extern "C" boundary, JSON marshalling, dispatching —
 * is generated and must not be hand-edited.
 */

import type { NativeManifest, NativeTypeName } from "./manifest";
import { rustTypeName } from "./manifest";

/** Cargo.toml for a Rust cdylib native module. */
export function generateCargoToml(manifest: NativeManifest): string {
  return `# Auto-generated by AsiJS — DO NOT EDIT
[package]
name = "${manifest.name}"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
`;
}

/**
 * Rust type for a JSON boundary param. Non-scalars arrive as serde_json::Value
 * and are converted to the declared type at the top of each stub.
 */
function paramDeserializeExpr(
  paramName: string,
  type: NativeTypeName,
  fnName: string,
): string {
  switch (type) {
    case "string":
      return `let ${paramName}: String = match args.get("${paramName}") {
  Some(serde_json::Value::String(s)) => s.clone(),
  _ => return Err(format!("[${fnName}] param \\"${paramName}\\": expected string"))};`;
    case "number":
      return `let ${paramName}: f64 = match args.get("${paramName}") {
  Some(serde_json::Value::Number(n)) => n.as_f64().unwrap_or(f64::NAN),
  _ => return Err(format!("[${fnName}] param \\"${paramName}\\": expected number"))};`;
    case "boolean":
      return `let ${paramName}: bool = match args.get("${paramName}") {
  Some(serde_json::Value::Bool(b)) => *b,
  _ => return Err(format!("[${fnName}] param \\"${paramName}\\": expected boolean"))};`;
    case "bytes":
      return `let ${paramName}: Vec<u8> = match args.get("${paramName}") {
  Some(serde_json::Value::Array(items)) => items.iter().filter_map(|v| v.as_u64().map(|n| n as u8)).collect(),
  _ => return Err(format!("[${fnName}] param \\"${paramName}\\": expected byte array"))};`;
    case "json":
      return `let ${paramName}: serde_json::Value = args.get("${paramName}").cloned().unwrap_or(serde_json::Value::Null);`;
  }
}

/** Build the dispatcher match arm for one function. */
function dispatcherArm(manifest: NativeManifest, fnName: string): string {
  const fn = manifest.functions.find((f) => f.name === fnName);
  if (!fn) return "";
  const paramNames = Object.keys(fn.params);
  const extracts = paramNames
    .map((p) => paramDeserializeExpr(p, fn.params[p]!, fnName))
    .join("\n  ");
  const callArgs = paramNames.join(", ");
  return `"${fnName}" => {
  ${extracts}
  let out = ${fnName}(${callArgs});
  Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
}`;
}

/** User stub body — the only part the user edits. */
function userStub(fnName: string): string {
  return `// TODO: implement the body of ${fnName}
unimplemented!("implement ${fnName}")`;
}

/** Generate src/lib.rs with stubs + dispatcher. */
export function generateLibRs(manifest: NativeManifest): string {
  const lines: string[] = [];
  lines.push(`// Auto-generated by AsiJS — DO NOT EDIT the FFI section below.
// Your code: fill in the bodies of the functions marked with TODO.
// Re-run "asi native scaffold ${manifest.lang}" to regenerate the FFI glue.`);
  lines.push("");
  lines.push(`use serde::Serialize;`);
  lines.push(`use std::ffi::{CStr, CString};`);
  lines.push(`use std::os::raw::c_char;`);
  lines.push("");
  lines.push(`/// JSON-RPC-style request: { "fn": name, "args": { ... } }`);
  lines.push(`#[derive(Serialize)]`);
  lines.push(`struct AsijsResponse {`);
  lines.push(`  ok: bool,`);
  lines.push(`  result: Option<serde_json::Value>,`);
  lines.push(`  error: Option<String>,`);
  lines.push(`}`);
  lines.push("");
  lines.push(`// ====================================================================`);
  lines.push(`// Your functions — edit the bodies below (signatures are generated)`);
  lines.push(`// ====================================================================`);
  lines.push("");

  for (const fn of manifest.functions) {
    const params = Object.entries(fn.params)
      .map(([name, type]) => `${name}: ${rustTypeName(type)}`)
      .join(", ");
    lines.push(`pub fn ${fn.name}(${params}) -> ${rustTypeName(fn.returns)} {`);
    lines.push(`  ${userStub(fn.name)}`);
    lines.push(`}`);
    lines.push("");
  }

  lines.push(`// ====================================================================`);
  lines.push(`// FFI boundary — DO NOT EDIT`);
  lines.push(`// ====================================================================`);
  lines.push(`fn dispatch(name: &str, args: &serde_json::Value) -> Result<serde_json::Value, String> {`);
  lines.push(`  match name {`);
  for (const fn of manifest.functions) {
    lines.push(`    ${dispatcherArm(manifest, fn.name)}`);
  }
  lines.push(`    _ => Err(format!("unknown native function: {}", name)),`);
  lines.push(`  }`);
  lines.push(`}`);
  lines.push("");
  lines.push(`/// Entry point: input = JSON string of { "fn": ..., "args": ... }`);
  lines.push(`/// Returns a malloc'd C string with the JSON response (free with asijs_free).`);
  lines.push(`#[unsafe(no_mangle)]`);
  lines.push(`pub extern "C" fn asijs_call(input: *const c_char) -> *mut c_char {`);
  lines.push(`  let result: AsijsResponse = if input.is_null() {`);
  lines.push(`    AsijsResponse { ok: false, result: None, error: Some("null input".into()) }`);
  lines.push(`  } else {`);
  lines.push(`    match unsafe { CStr::from_ptr(input) }.to_str() {`);
  lines.push(`      Ok(s) => match serde_json::from_str::<serde_json::Value>(s) {`);
  lines.push(`        Ok(req) => {`);
  lines.push(`          let name = req.get("fn").and_then(|v| v.as_str()).unwrap_or("");`);
  lines.push(`          let args = req.get("args").cloned().unwrap_or(serde_json::Value::Null);`);
  lines.push(`          match dispatch(name, &args) {`);
  lines.push(`            Ok(result) => AsijsResponse { ok: true, result: Some(result), error: None },`);
  lines.push(`            Err(error) => AsijsResponse { ok: false, result: None, error: Some(error) },`);
  lines.push(`          }`);
  lines.push(`        }`);
  lines.push(`        Err(e) => AsijsResponse { ok: false, result: None, error: Some(format!("invalid JSON: {}", e)) },`);
  lines.push(`      }`);
  lines.push(`      Err(e) => AsijsResponse { ok: false, result: None, error: Some(format!("invalid UTF-8: {}", e)) },`);
  lines.push(`    }`);
  lines.push(`  };`);
  lines.push(`  match serde_json::to_string(&result) {`);
  lines.push(`    Ok(json) => match CString::new(json) {`);
  lines.push(`      Ok(cstr) => cstr.into_raw(),`);
  lines.push(`      Err(_) => std::ptr::null_mut(),`);
  lines.push(`    },`);
  lines.push(`    Err(e) => {`);
  lines.push(`      let err = AsijsResponse { ok: false, result: None, error: Some(format!("serialize error: {}", e)) };`);
  lines.push(`      let json = serde_json::to_string(&err).unwrap_or_else(|_| "{\\"ok\\":false}".into());`);
  lines.push(`      CString::new(json).map(|c| c.into_raw()).unwrap_or(std::ptr::null_mut())`);
  lines.push(`    }`);
  lines.push(`  }`);
  lines.push(`}`);
  lines.push("");
  lines.push(`/// Free a pointer returned by asijs_call.`);
  lines.push(`#[unsafe(no_mangle)]`);
  lines.push(`pub extern "C" fn asijs_free(ptr: *mut c_char) {`);
  lines.push(`  if !ptr.is_null() {`);
  lines.push(`    unsafe { drop(CString::from_raw(ptr)); }`);
  lines.push(`  }`);
  lines.push(`}`);
  lines.push("");

  return lines.join("\n");
}
