/**
 * Native / Polyglot Modules — Go stub generator (2.1)
 *
 * Generates a Go c-shared module from a manifest:
 *   - `native/go.mod` — module file
 *   - `native/main.go` — `//export` FFI entry + JSON dispatcher
 *
 * Build: `go build -buildmode=c-shared -o <lib> .`
 *
 * The user edits ONLY the function bodies (marked with `// TODO: implement`).
 */

import type { NativeManifest, NativeTypeName } from "./manifest";

/** Go type for a boundary type. */
export function goTypeName(t: NativeTypeName): string {
  switch (t) {
    case "string":
      return "string";
    case "number":
      return "float64";
    case "boolean":
      return "bool";
    case "bytes":
      return "[]byte";
    case "json":
      return "any";
  }
}

/** go.mod for a c-shared native module. */
export function generateGoMod(manifest: NativeManifest): string {
  return `module ${manifest.name}

go 1.21
`;
}

/** Extract a param from the args map, with a typed assertion. */
function paramExtractGo(
  paramName: string,
  type: NativeTypeName,
  fnName: string,
): string {
  const target = goTypeName(type);
  switch (type) {
    case "string":
      return `\t${paramName}, err := argString(args, "${paramName}", "${fnName}")
\tif err != nil {
\t\treturn nil, err
\t}`;
    case "number":
      return `\t${paramName}, err := argNumber(args, "${paramName}", "${fnName}")
\tif err != nil {
\t\treturn nil, err
\t}`;
    case "boolean":
      return `\t${paramName}, err := argBool(args, "${paramName}", "${fnName}")
\tif err != nil {
\t\treturn nil, err
\t}`;
    case "bytes":
      return `\t${paramName}, err := argBytes(args, "${paramName}", "${fnName}")
\tif err != nil {
\t\treturn nil, err
\t}`;
    case "json":
      return `\t${paramName}, err := argJSON(args, "${paramName}", "${fnName}")
\tif err != nil {
\t\treturn nil, err
\t}`;
  }
}

/** Dispatch match arm for one function. */
function dispatchArmGo(manifest: NativeManifest, fnName: string): string {
  const fn = manifest.functions.find((f) => f.name === fnName);
  if (!fn) return "";
  const extracts = Object.keys(fn.params)
    .map((p) => paramExtractGo(p, fn.params[p]!, fnName))
    .join("\n");
  const callArgs = Object.keys(fn.params).join(", ");
  return `case "${fnName}":
${extracts}
\treturn ${fnName}(${callArgs}), nil`;
}

/** User stub body — the only part the user edits. */
function userStubGo(fnName: string): string {
  return `// TODO: implement the body of ${fnName}
\tpanic("implement ${fnName}")`;
}

/** Generate main.go with stubs + dispatcher. */
export function generateMainGo(manifest: NativeManifest): string {
  const lines: string[] = [];
  lines.push(`// Auto-generated by AsiJS — DO NOT EDIT the FFI section below.`);
  lines.push(`// Your code: fill in the bodies of the functions marked with TODO.`);
  lines.push(`// Re-run "asi native scaffold ${manifest.lang}" to regenerate the FFI glue.`);
  lines.push(`package main`);
  lines.push(``);
  lines.push(`/*`);
  lines.push(`#include <stdlib.h>`);
  lines.push(`*/`);
  lines.push(`import "C"`);
  lines.push(``);
  lines.push(`import (`);
  lines.push(`\t"encoding/json"`);
  lines.push(`\t"fmt"`);
  lines.push(`\t"unsafe"`);
  lines.push(`)`);
  lines.push(``);
  lines.push(`type asijsResponse struct {`);
  lines.push(`\tOk     bool            \`json:"ok"\``);
  lines.push(`\tResult json.RawMessage \`json:"result,omitempty"\``);
  lines.push(`\tError  string          \`json:"error,omitempty"\``);
  lines.push(`}`);
  lines.push(``);
  lines.push(`// ====================================================================`);
  lines.push(`// Your functions — edit the bodies below (signatures are generated)`);
  lines.push(`// ====================================================================`);
  lines.push(``);

  for (const fn of manifest.functions) {
    const params = Object.entries(fn.params)
      .map(([name, type]) => `${name} ${goTypeName(type)}`)
      .join(", ");
    lines.push(`func ${fn.name}(${params}) ${goTypeName(fn.returns)} {`);
    lines.push(`\t${userStubGo(fn.name)}`);
    lines.push(`}`);
    lines.push(``);
  }

  lines.push(`// ====================================================================`);
  lines.push(`// FFI boundary — DO NOT EDIT`);
  lines.push(`// ====================================================================`);
  lines.push(`func dispatch(name string, args map[string]any) (any, error) {`);
  lines.push(`\tswitch name {`);
  for (const fn of manifest.functions) {
    lines.push(`\t\t${dispatchArmGo(manifest, fn.name)}`);
  }
  lines.push(`\tdefault:`);
  lines.push(`\t\treturn nil, fmt.Errorf("unknown native function: %s", name)`);
  lines.push(`\t}`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`//export asijs_call`);
  lines.push(`func asijs_call(input *C.char) *C.char {`);
  lines.push(`\tvar req struct {`);
  lines.push(`\t\tFn   string         \`json:"fn"\``);
  lines.push(`\t\tArgs map[string]any \`json:"args"\``);
  lines.push(`\t}`);
  lines.push(`\tif err := json.Unmarshal([]byte(C.GoString(input)), &req); err != nil {`);
  lines.push(`\t\treturn cString(asijsResponse{Ok: false, Error: "invalid JSON: " + err.Error()})`);
  lines.push(`\t}`);
  lines.push(`\tresult, err := dispatch(req.Fn, req.Args)`);
  lines.push(`\tif err != nil {`);
  lines.push(`\t\treturn cString(asijsResponse{Ok: false, Error: err.Error()})`);
  lines.push(`\t}`);
  lines.push(`\tout, err := json.Marshal(result)`);
  lines.push(`\tif err != nil {`);
  lines.push(`\t\treturn cString(asijsResponse{Ok: false, Error: "marshal error: " + err.Error()})`);
  lines.push(`\t}`);
  lines.push(`\treturn cString(asijsResponse{Ok: true, Result: out})`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`//export asijs_free`);
  lines.push(`func asijs_free(ptr *C.char) {`);
  lines.push(`\tC.free(unsafe.Pointer(ptr))`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`func cString(resp asijsResponse) *C.char {`);
  lines.push(`\tb, err := json.Marshal(resp)`);
  lines.push(`\tif err != nil {`);
  lines.push(`\t\treturn C.CString(\`{"ok":false,"error":"marshal error"}\`)`);
  lines.push(`\t}`);
  lines.push(`\treturn C.CString(string(b))`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`func argString(args map[string]any, key, fn string) (string, error) {`);
  lines.push(`\tv, ok := args[key]`);
  lines.push(`\tif !ok {`);
  lines.push(`\t\treturn "", fmt.Errorf("[%s] param %q: missing", fn, key)`);
  lines.push(`\t}`);
  lines.push(`\ts, ok := v.(string)`);
  lines.push(`\tif !ok {`);
  lines.push(`\t\treturn "", fmt.Errorf("[%s] param %q: expected string", fn, key)`);
  lines.push(`\t}`);
  lines.push(`\treturn s, nil`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`func argNumber(args map[string]any, key, fn string) (float64, error) {`);
  lines.push(`\tv, ok := args[key]`);
  lines.push(`\tif !ok {`);
  lines.push(`\t\treturn 0, fmt.Errorf("[%s] param %q: missing", fn, key)`);
  lines.push(`\t}`);
  lines.push(`\tn, ok := v.(float64)`);
  lines.push(`\tif !ok {`);
  lines.push(`\t\treturn 0, fmt.Errorf("[%s] param %q: expected number", fn, key)`);
  lines.push(`\t}`);
  lines.push(`\treturn n, nil`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`func argBool(args map[string]any, key, fn string) (bool, error) {`);
  lines.push(`\tv, ok := args[key]`);
  lines.push(`\tif !ok {`);
  lines.push(`\t\treturn false, fmt.Errorf("[%s] param %q: missing", fn, key)`);
  lines.push(`\t}`);
  lines.push(`\tb, ok := v.(bool)`);
  lines.push(`\tif !ok {`);
  lines.push(`\t\treturn false, fmt.Errorf("[%s] param %q: expected boolean", fn, key)`);
  lines.push(`\t}`);
  lines.push(`\treturn b, nil`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`func argBytes(args map[string]any, key, fn string) ([]byte, error) {`);
  lines.push(`\tv, ok := args[key]`);
  lines.push(`\tif !ok {`);
  lines.push(`\t\treturn nil, fmt.Errorf("[%s] param %q: missing", fn, key)`);
  lines.push(`\t}`);
  lines.push(`\titems, ok := v.([]any)`);
  lines.push(`\tif !ok {`);
  lines.push(`\t\treturn nil, fmt.Errorf("[%s] param %q: expected byte array", fn, key)`);
  lines.push(`\t}`);
  lines.push(`\tout := make([]byte, len(items))`);
  lines.push(`\tfor i, item := range items {`);
  lines.push(`\t\tn, ok := item.(float64)`);
  lines.push(`\t\tif !ok {`);
  lines.push(`\t\t\treturn nil, fmt.Errorf("[%s] param %q: byte %d is not a number", fn, key, i)`);
  lines.push(`\t\t}`);
  lines.push(`\t\tout[i] = byte(n)`);
  lines.push(`\t}`);
  lines.push(`\treturn out, nil`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`func argJSON(args map[string]any, key, fn string) (any, error) {`);
  lines.push(`\tv, ok := args[key]`);
  lines.push(`\tif !ok {`);
  lines.push(`\t\treturn nil, fmt.Errorf("[%s] param %q: missing", fn, key)`);
  lines.push(`\t}`);
  lines.push(`\treturn v, nil`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`func main() {}`);
  lines.push(``);

  return lines.join("\n");
}
