/**
 * Native / Polyglot Modules — sidecar server generators (2.2)
 *
 * Interpreted languages (Python/Ruby/PHP) run as sidecar processes: AsiJS
 * spawns the interpreter with a generated `server.<ext>` script and speaks
 * JSON-RPC over stdio (one JSON object per line). The user implements only
 * the function bodies; the dispatcher, param-type tables and bytes
 * (de)serialization are generated from the manifest.
 *
 * Wire format: plain JSON. `bytes` values travel as base64 strings — the
 * manifest types tell the script exactly which params/results are bytes,
 * so no marker objects leak into user code.
 */

import type { NativeManifest, NativeTypeName } from "./manifest";
import { tsTypeName } from "./manifest";

// ============================================================================
// Identifier safety (reserved words per language)
// ============================================================================

const PY_KEYWORDS = new Set([
  "False", "None", "True", "and", "as", "assert", "async", "await", "break",
  "class", "continue", "def", "del", "elif", "else", "except", "finally",
  "for", "from", "global", "if", "import", "in", "is", "lambda", "nonlocal",
  "not", "or", "pass", "raise", "return", "try", "while", "with", "yield",
]);

const RB_KEYWORDS = new Set([
  "alias", "and", "begin", "break", "case", "class", "def", "defined?", "do",
  "else", "elsif", "end", "ensure", "false", "for", "if", "in", "module",
  "next", "nil", "not", "or", "redo", "rescue", "retry", "return", "self",
  "super", "then", "true", "undef", "unless", "until", "when", "while",
  "yield", "BEGIN", "END", "__FILE__", "__LINE__",
]);

const PHP_KEYWORDS = new Set([
  "abstract", "and", "array", "as", "break", "callable", "case", "catch",
  "class", "clone", "const", "continue", "declare", "default", "do", "echo",
  "else", "elseif", "empty", "enddeclare", "endfor", "endforeach", "endif",
  "endswitch", "endwhile", "enum", "eval", "exit", "extends", "final",
  "finally", "fn", "for", "foreach", "function", "global", "goto", "if",
  "implements", "include", "include_once", "instanceof", "insteadof",
  "interface", "isset", "list", "match", "namespace", "new", "or", "print",
  "private", "protected", "public", "readonly", "require", "require_once",
  "return", "static", "switch", "throw", "trait", "try", "unset", "use",
  "var", "while", "xor", "yield",
]);

/** Make an identifier safe for a language's reserved words. */
function safeIdent(name: string, keywords: Set<string>): string {
  return keywords.has(name) ? `${name}_` : name;
}

/** Build the param-type table lines for a language. */
function paramTypesTable(
  manifest: NativeManifest,
  fmt: (name: string, type: NativeTypeName) => string,
  wrap: (fnName: string, params: string) => string = (fnName, params) => `"${fnName}": { ${params} }`,
): string {
  return manifest.functions
    .map((fn) => {
      const params = Object.entries(fn.params)
        .map(([n, t]) => fmt(n, t))
        .join(", ");
      return `    ${wrap(fn.name, params)},`;
    })
    .join("\n");
}

/** Build the return-type table lines. */
function returnTypesTable(
  manifest: NativeManifest,
  fmt: (type: NativeTypeName) => string,
  wrap: (fnName: string, value: string) => string = (fnName, value) => `"${fnName}": ${value}`,
): string {
  return manifest.functions
    .map((fn) => `    ${wrap(fn.name, fmt(fn.returns))},`)
    .join("\n");
}

// ============================================================================
// Python
// ============================================================================

/**
 * Generate `server.py` — JSON-RPC dispatcher + typed stubs for the manifest
 * functions. The user implements only the function bodies.
 */
export function generatePythonServer(manifest: NativeManifest): string {
  const lines: string[] = [];
  lines.push(`#!/usr/bin/env python3`);
  lines.push(`# Auto-generated by AsiJS — DO NOT EDIT the dispatcher below.`);
  lines.push(`# Implement the function bodies, then run your app: the interpreter`);
  lines.push(`# is spawned automatically and speaks JSON-RPC over stdio.`);
  lines.push(``);
  lines.push(`import base64`);
  lines.push(`import json`);
  lines.push(`import sys`);
  lines.push(``);
  lines.push(``);
  for (const fn of manifest.functions) {
    const params = Object.entries(fn.params)
      .map(([n]) => safeIdent(n, PY_KEYWORDS))
      .join(", ");
    lines.push(`def ${safeIdent(fn.name, PY_KEYWORDS)}(${params}):`);
    lines.push(`    # TODO: implement the body of ${fn.name}`);
    lines.push(`    raise NotImplementedError("implement ${fn.name}")`);
    lines.push(``);
    lines.push(``);
  }
  lines.push(`_PARAM_TYPES = {`);
  lines.push(paramTypesTable(manifest, (n, t) => `"${n}": "${t}"`));
  lines.push(`}`);
  lines.push(``);
  lines.push(`_RETURN_TYPES = {`);
  lines.push(returnTypesTable(manifest, (t) => `"${t}"`));
  lines.push(`}`);
  lines.push(``);
  lines.push(`_HANDLERS = {`);
  for (const fn of manifest.functions) {
    lines.push(`    "${fn.name}": ${safeIdent(fn.name, PY_KEYWORDS)},`);
  }
  lines.push(`}`);
  lines.push(``);
  lines.push(``);
  lines.push(`def _coerce_args(fn_name, args):`);
  lines.push(`    """Decode wire values: bytes params arrive as base64 strings."""`);
  lines.push(`    types = _PARAM_TYPES.get(fn_name, {})`);
  lines.push(`    out = {}`);
  lines.push(`    for key, value in args.items():`);
  lines.push(`        if types.get(key) == "bytes":`);
  lines.push(`            out[key] = base64.b64decode(value) if isinstance(value, str) else value`);
  lines.push(`        else:`);
  lines.push(`            out[key] = value`);
  lines.push(`    return out`);
  lines.push(``);
  lines.push(``);
  lines.push(`def _coerce_result(fn_name, value):`);
  lines.push(`    """Encode a bytes result as a base64 string for the wire."""`);
  lines.push(`    if _RETURN_TYPES.get(fn_name) == "bytes":`);
  lines.push(`        if isinstance(value, (bytes, bytearray, memoryview)):`);
  lines.push(`            return base64.b64encode(bytes(value)).decode("ascii")`);
  lines.push(`    return value`);
  lines.push(``);
  lines.push(``);
  lines.push(`def _main():`);
  lines.push(`    for line in sys.stdin:`);
  lines.push(`        line = line.strip()`);
  lines.push(`        if not line:`);
  lines.push(`            continue`);
  lines.push(`        req_id = None`);
  lines.push(`        try:`);
  lines.push(`            req = json.loads(line)`);
  lines.push(`            req_id = req.get("id")`);
  lines.push(`            handler = _HANDLERS.get(req.get("fn"))`);
  lines.push(`            if handler is None:`);
  lines.push(`                raise ValueError("unknown function: %s" % req.get("fn"))`);
  lines.push(`            args = req.get("args") or {}`);
  lines.push(`            result = handler(**_coerce_args(req.get("fn"), args))`);
  lines.push(`            sys.stdout.write(json.dumps({`);
  lines.push(`                "id": req_id, "ok": True,`);
  lines.push(`                "result": _coerce_result(req.get("fn"), result),`);
  lines.push(`            }) + "\\n")`);
  lines.push(`        except Exception as exc:  # noqa: BLE001 — report, keep serving`);
  lines.push(`            sys.stdout.write(json.dumps({`);
  lines.push(`                "id": req_id, "ok": False, "error": str(exc),`);
  lines.push(`            }) + "\\n")`);
  lines.push(`        sys.stdout.flush()`);
  lines.push(``);
  lines.push(``);
  lines.push(`if __name__ == "__main__":`);
  lines.push(`    _main()`);
  lines.push(``);
  return lines.join("\n");
}

// ============================================================================
// Ruby
// ============================================================================

/**
 * Generate `server.rb` — JSON-RPC dispatcher + typed stubs.
 */
export function generateRubyServer(manifest: NativeManifest): string {
  const lines: string[] = [];
  lines.push(`#!/usr/bin/env ruby`);
  lines.push(`# Auto-generated by AsiJS — implement the function bodies, keep the dispatcher.`);
  lines.push(`require "json"`);
  lines.push(`require "base64"`);
  lines.push(``);
  lines.push(``);
  for (const fn of manifest.functions) {
    // Ruby 3 splits kwargs from positional args — the dispatcher calls
    // `handler.call(**args)`, so stubs must declare keyword params (`a:`).
    const params = Object.entries(fn.params)
      .map(([n]) => `${safeIdent(n, RB_KEYWORDS)}:`)
      .join(", ");
    lines.push(`def ${safeIdent(fn.name, RB_KEYWORDS)}(${params})`);
    lines.push(`  # TODO: implement the body of ${fn.name}`);
    // RuntimeError (not NotImplementedError) — it's a StandardError, so the
    // dispatcher's `rescue StandardError` catches it and reports via JSON.
    lines.push(`  raise "implement ${fn.name}"`);
    lines.push(`end`);
    lines.push(``);
    lines.push(``);
  }
  lines.push(`PARAM_TYPES = {`);
  lines.push(paramTypesTable(manifest, (n, t) => `"${n}" => "${t}"`, (fnName, params) => `"${fnName}" => { ${params} }`));
  lines.push(`}.freeze`);
  lines.push(``);
  lines.push(`RETURN_TYPES = {`);
  lines.push(returnTypesTable(manifest, (t) => `"${t}"`, (fnName, value) => `"${fnName}" => ${value}`));
  lines.push(`}.freeze`);
  lines.push(``);
  lines.push(`HANDLERS = {`);
  for (const fn of manifest.functions) {
    lines.push(`  "${fn.name}" => method(:${safeIdent(fn.name, RB_KEYWORDS)}),`);
  }
  lines.push(`}.freeze`);
  lines.push(``);
  lines.push(``);
  lines.push(`def coerce_args(fn_name, args)`);
  lines.push(`  # Decode wire values: bytes params arrive as base64 strings.`);
  lines.push(`  types = PARAM_TYPES[fn_name] || {}`);
  lines.push(`  args.each_with_object({}) do |(key, value), out|`);
  lines.push(`    out[key] = types[key] == "bytes" ? Base64.decode64(value) : value`);
  lines.push(`  end`);
  lines.push(`end`);
  lines.push(``);
  lines.push(``);
  lines.push(`def coerce_result(fn_name, value)`);
  lines.push(`  # Encode a binary String result as a base64 string for the wire.`);
  lines.push(`  if RETURN_TYPES[fn_name] == "bytes" && value.is_a?(String) && value.encoding == Encoding::BINARY`);
  lines.push(`    Base64.strict_encode64(value)`);
  lines.push(`  else`);
  lines.push(`    value`);
  lines.push(`  end`);
  lines.push(`end`);
  lines.push(``);
  lines.push(``);
  lines.push(`STDOUT.sync = true`);
  lines.push(``);
  lines.push(`STDIN.each_line do |line|`);
  lines.push(`  line = line.strip`);
  lines.push(`  next if line.empty?`);
  lines.push(`  req_id = nil`);
  lines.push(`  begin`);
  lines.push(`    req = JSON.parse(line)`);
  lines.push(`    req_id = req["id"]`);
  lines.push(`    handler = HANDLERS[req["fn"]]`);
  lines.push(`    raise "unknown function: \#{req["fn"]}" unless handler`);
  lines.push(`    args = coerce_args(req["fn"], req["args"] || {}).transform_keys(&:to_sym)`);
  lines.push(`    result = handler.call(**args)`);
  lines.push(`    STDOUT.puts(JSON.generate({ "id" => req_id, "ok" => true, "result" => coerce_result(req["fn"], result) }))`);
  lines.push(`  rescue StandardError => e`);
  lines.push(`    STDOUT.puts(JSON.generate({ "id" => req_id, "ok" => false, "error" => e.message }))`);
  lines.push(`  end`);
  lines.push(`end`);
  lines.push(``);
  return lines.join("\n");
}

// ============================================================================
// PHP
// ============================================================================

/**
 * Generate `server.php` — JSON-RPC dispatcher + typed stubs.
 */
export function generatePhpServer(manifest: NativeManifest): string {
  const lines: string[] = [];
  lines.push(`<?php`);
  lines.push(`// Auto-generated by AsiJS — implement the function bodies, keep the dispatcher.`);
  lines.push(`declare(strict_types=1);`);
  lines.push(``);
  lines.push(``);
  for (const fn of manifest.functions) {
    const params = Object.entries(fn.params)
      .map(([n]) => `$${safeIdent(n, PHP_KEYWORDS)}`)
      .join(", ");
    lines.push(`function ${safeIdent(fn.name, PHP_KEYWORDS)}(${params}) {`);
    lines.push(`    // TODO: implement the body of ${fn.name}`);
    lines.push(`    throw new RuntimeException("implement ${fn.name}");`);
    lines.push(`}`);
    lines.push(``);
    lines.push(``);
  }
  lines.push(`$PARAM_TYPES = [`);
  lines.push(paramTypesTable(manifest, (n, t) => `"${n}" => "${t}"`, (fnName, params) => `"${fnName}" => [ ${params} ]`));
  lines.push(`];`);
  lines.push(``);
  lines.push(`$RETURN_TYPES = [`);
  lines.push(returnTypesTable(manifest, (t) => `"${t}"`, (fnName, value) => `"${fnName}" => ${value}`));
  lines.push(`];`);
  lines.push(``);
  lines.push(`$HANDLERS = [`);
  for (const fn of manifest.functions) {
    lines.push(`    "${fn.name}" => "${safeIdent(fn.name, PHP_KEYWORDS)}",`);
  }
  lines.push(`];`);
  lines.push(``);
  lines.push(``);
  lines.push(`function coerce_args(string $fnName, array $args): array {`);
  lines.push(`    $types = $GLOBALS["PARAM_TYPES"][$fnName] ?? [];`);
  lines.push(`    foreach ($args as $key => $value) {`);
  lines.push(`        if (($types[$key] ?? null) === "bytes") {`);
  lines.push(`            $args[$key] = base64_decode((string) $value);`);
  lines.push(`        }`);
  lines.push(`    }`);
  lines.push(`    return $args;`);
  lines.push(`}`);
  lines.push(``);
  lines.push(``);
  lines.push(`function coerce_result(string $fnName, $value) {`);
  lines.push(`    if (($GLOBALS["RETURN_TYPES"][$fnName] ?? null) === "bytes") {`);
  lines.push(`        return base64_encode((string) $value);`);
  lines.push(`    }`);
  lines.push(`    return $value;`);
  lines.push(`}`);
  lines.push(``);
  lines.push(``);
  lines.push(`while (($line = fgets(STDIN)) !== false) {`);
  lines.push(`    $line = trim($line);`);
  lines.push(`    if ($line === "") { continue; }`);
  lines.push(`    $reqId = null;`);
  lines.push(`    try {`);
  lines.push(`        $req = json_decode($line, true);`);
  lines.push(`        $reqId = $req["id"] ?? null;`);
  lines.push(`        $fn = $req["fn"] ?? null;`);
  lines.push(`        if (!is_string($fn) || !array_key_exists($fn, $GLOBALS["HANDLERS"])) {`);
  lines.push(`            throw new RuntimeException("unknown function: " . $fn);`);
  lines.push(`        }`);
  lines.push(`        $args = coerce_args($fn, $req["args"] ?? []);`);
  lines.push(`        $result = call_user_func_array($GLOBALS["HANDLERS"][$fn], $args);`);
  lines.push(`        fwrite(STDOUT, json_encode([`);
  lines.push(`            "id" => $reqId, "ok" => true,`);
  lines.push(`            "result" => coerce_result($fn, $result),`);
  lines.push(`        ]) . "\\n");`);
  lines.push(`    } catch (Throwable $e) {`);
  lines.push(`        fwrite(STDOUT, json_encode(["id" => $reqId, "ok" => false, "error" => $e->getMessage()]) . "\\n");`);
  lines.push(`    }`);
  lines.push(`    fflush(STDOUT);`);
  lines.push(`}`);
  lines.push(``);
  return lines.join("\n");
}

// ============================================================================
// TypeScript client (direct use, mirrors the ctx.native interface)
// ============================================================================

/** JS-identifier-safe PascalCase for a module name. */
function pascalName(name: string): string {
  const ident = name.replace(/[^a-zA-Z0-9_]/g, "_");
  return ident.charAt(0).toUpperCase() + ident.slice(1);
}

/**
 * Generate `src/generated.ts` for a sidecar module — a typed wrapper around
 * `createSidecarClient`. This is the direct-import counterpart to the FFI
 * wrapper generated by `generateTsWrapper`; `ctx.native` uses the same
 * client internally.
 */
export function generateSidecarTsClient(manifest: NativeManifest): string {
  const header = `// Auto-generated by AsiJS — DO NOT EDIT
// Sidecar client for "${manifest.name}" (${manifest.lang}).
// Regenerate with: asi native build
`;
  const lines: string[] = [];
  lines.push(header);
  lines.push(``);
  lines.push(`import { createSidecarClient, type NativeModule } from "asijs/native";`);
  lines.push(``);
  lines.push(`export interface ${pascalName(manifest.name)}Functions {`);
  for (const fn of manifest.functions) {
    const params = Object.entries(fn.params)
      .map(([n, t]) => `${n}: ${tsTypeName(t)}`)
      .join(", ");
    lines.push(`  ${fn.name}(${params}): Promise<${tsTypeName(fn.returns)}>;`);
  }
  lines.push(`}`);
  lines.push(``);
  lines.push(`export interface ModuleConfig {`);
  lines.push(`  /** Project root (default: process.cwd()). */`);
  lines.push(`  cwd?: string;`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`export function loadModule(`);
  lines.push(`  opts: ModuleConfig = {},`);
  lines.push(`): NativeModule & ${pascalName(manifest.name)}Functions {`);
  const manifestJson = JSON.stringify(manifest, null, 2).split("\n").join("\n  ");
  lines.push(`  const manifest = ${manifestJson};`);
  lines.push(`  return createSidecarClient(manifest, opts) as NativeModule & ${pascalName(manifest.name)}Functions;`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`export default loadModule;`);
  lines.push(``);
  return lines.join("\n");
}
