/**
 * Native / Polyglot Modules — TypeScript wrapper generator (1.3)
 *
 * Generates a `native/generated.ts` module from the manifest: a typed
 * `bun:ffi` wrapper around the compiled shared library. Each manifest
 * function becomes a typed method; JSON marshalling is generated once.
 *
 * The wrapper is the only place that touches dlopen — user code calls
 * `ctx.native.<fn>(...)` (or imports `native` directly) and gets typed
 * results.
 */

import type { NativeManifest, NativeTypeName } from "./manifest";
import { tsTypeName } from "./manifest";

/** Sanitize a manifest name into a JS identifier-safe suffix. */
function safeIdent(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, "_");
}

/** Marshal a JS value into a JSON-encodable form for the Rust boundary. */
function toJsonExpr(expr: string, type: NativeTypeName): string {
  switch (type) {
    case "string":
    case "number":
    case "boolean":
    case "json":
      return expr;
    case "bytes":
      // Byte arrays are passed as arrays of numbers (JSON boundary).
      return `Array.from(${expr})`;
  }
}

/** Unmarshal a JSON response value into the declared TS type. */
function fromJsonExpr(expr: string, type: NativeTypeName): string {
  switch (type) {
    case "string":
      return `String(${expr})`;
    case "number":
      return `Number(${expr})`;
    case "boolean":
      return `Boolean(${expr})`;
    case "bytes":
      return `new Uint8Array(${expr} as number[])`;
    case "json":
      return expr;
  }
}

/**
 * Generate the full `generated.ts` wrapper source.
 *
 * @param manifest       Parsed manifest
 * @param libPathExpr    JS expression for the shared library path (e.g. a
 *                       `join(__dirname, "lib.so")` expression or a literal)
 */
export function generateTsWrapper(
  manifest: NativeManifest,
  libPathExpr: string,
): string {
  const header = `// Auto-generated by AsiJS — DO NOT EDIT
// Native wrapper for "${manifest.name}" (${manifest.lang}).
// Regenerate with: asi native build
`;
  const lines: string[] = [];
  lines.push(header);
  lines.push("");
  lines.push(`import { dlopen, ptr, toBuffer, utf8ToString } from "bun:ffi";`);
  lines.push(`import { join } from "path";`);
  lines.push("");
  lines.push(`const LIB_PATH = ${libPathExpr};`);
  lines.push("");
  lines.push(`interface AsijsResult {`);
  lines.push(`  ok: boolean;`);
  lines.push(`  result?: unknown;`);
  lines.push(`  error?: string;`);
  lines.push(`}`);
  lines.push("");
  lines.push(`let _lib: ReturnType<typeof dlopen> | null = null;`);
  lines.push(`function lib() {`);
  lines.push(`  if (!_lib) {`);
  lines.push(`    _lib = dlopen(LIB_PATH, {`);
  lines.push(`      asijs_call: { args: ["ptr"], returns: "ptr" },`);
  lines.push(`      asijs_free: { args: ["ptr"], returns: "void" },`);
  lines.push(`    });`);
  lines.push(`  }`);
  lines.push(`  return _lib;`);
  lines.push(`}`);
  lines.push("");
  lines.push(`function invoke(fnName: string, args: Record<string, unknown>): unknown {`);
  lines.push(`  const payload = JSON.stringify({ fn: fnName, args });`);
  lines.push(`  const inputBuf = Buffer.from(payload, "utf-8");`);
  lines.push(`  const inputPtr = ptr(inputBuf);`);
  lines.push(`  const outPtr = lib().symbols.asijs_call(inputPtr) as Buffer | null;`);
  lines.push(`  if (!outPtr) {`);
  lines.push(`    throw new Error(\`[native:\${fnName}] null response from library\`);`);
  lines.push(`  }`);
  lines.push(`  try {`);
  lines.push(`    const raw = toBuffer(outPtr as any);`);
  lines.push(`    const text = utf8ToString(raw);`);
  lines.push(`    const res = JSON.parse(text) as AsijsResult;`);
  lines.push(`    if (!res.ok) {`);
  lines.push(`      throw new Error(\`[native:\${fnName}] \${res.error ?? "native error"}\`);`);
  lines.push(`    }`);
  lines.push(`    return res.result;`);
  lines.push(`  } finally {`);
  lines.push(`    lib().symbols.asijs_free(outPtr as any);`);
  lines.push(`  }`);
  lines.push(`}`);
  lines.push("");
  lines.push(`/**`);
  lines.push(` * Typed native API for "${manifest.name}".`);
  lines.push(` * Functions are generated from the manifest — see native/manifest.json.`);
  lines.push(` */`);
  lines.push(`export const native = {`);
  for (const fn of manifest.functions) {
    const params = Object.entries(fn.params);
    const paramDecls = params
      .map(([name, type]) => `${name}: ${tsTypeName(type)}`)
      .join(", ");
    const argObj = params.length
      ? `{ ${params
          .map(([name, type]) => `${JSON.stringify(name)}: ${toJsonExpr(name, type)}`)
          .join(", ")} }`
      : `{}`;
    const resultExpr = `invoke(${JSON.stringify(fn.name)}, ${argObj})`;
    const retStmt = `return ${fromJsonExpr(resultExpr, fn.returns)} as ${tsTypeName(fn.returns)};`;
    lines.push(`  ${safeIdent(fn.name)}(${paramDecls}): ${tsTypeName(fn.returns)} {`);
    lines.push(`    ${retStmt}`);
    lines.push(`  },`);
  }
  lines.push(`};`);
  lines.push("");
  lines.push(`export default native;`);
  lines.push("");

  return lines.join("\n");
}

/**
 * Default library file name for a compiled native module.
 * Mirrors the naming in the Rust build (cargo produces lib<name>.so/.dll).
 */
export function libFileName(manifest: NativeManifest): string {
  const base = `lib${manifest.name}`;
  return base; // platform extension added by the build step
}

/** Platform-specific shared-library extension. */
export function platformLibExt(): ".so" | ".dll" | ".dylib" {
  const platform = typeof process !== "undefined" ? process.platform : "";
  if (platform === "win32") return ".dll";
  if (platform === "darwin") return ".dylib";
  return ".so";
}

/** Default JS expression resolving the shared library path. */
export function defaultLibPathExpr(manifest: NativeManifest): string {
  const ext = platformLibExt();
  // cargo/go cdylib: `lib<name>` on POSIX, `<name>` on Windows
  const prefix = ext === ".dll" ? "" : "lib";
  const filename = `${prefix}${manifest.name}${ext}`;
  return `join(__dirname, ${JSON.stringify(filename)})`;
}
