// Auto-generated by AsiJS — DO NOT EDIT the FFI section below.
// Your code: fill in the bodies of the functions marked with TODO.
// Re-run "asi native scaffold c" to regenerate the FFI glue.

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>


/* ===== minimal JSON (embedded, valid C & C++) ===== */
typedef struct jval jval;
struct jval {
  int type;      /* 0 null, 1 bool, 2 num, 3 str, 4 arr, 5 obj */
  int boolean;
  double num;
  char *str;
  jval **items;  /* array items or object values */
  char **keys;   /* object keys (type==5) */
  size_t len;
};

static jval *jv_alloc(int type) {
  jval *v = (jval *)calloc(1, sizeof(jval));
  v->type = type;
  return v;
}

static void jv_free(jval *v) {
  if (!v) return;
  if (v->str) free(v->str);
  if (v->items) {
    size_t i;
    for (i = 0; i < v->len; i++) jv_free(v->items[i]);
    free(v->items);
  }
  if (v->keys) {
    size_t i;
    for (i = 0; i < v->len; i++) free(v->keys[i]);
    free(v->keys);
  }
  free(v);
}

static jval *jv_str_new(const char *s) {
  jval *v = jv_alloc(3);
  v->str = (char *)malloc(strlen(s) + 1);
  strcpy(v->str, s);
  return v;
}

static void jv_push(jval *arr, jval *item) {
  arr->items = (jval **)realloc(arr->items, (arr->len + 1) * sizeof(jval *));
  arr->items[arr->len++] = item;
}

static void jv_set(jval *obj, const char *key, jval *val) {
  obj->keys = (char **)realloc(obj->keys, (obj->len + 1) * sizeof(char *));
  obj->items = (jval **)realloc(obj->items, (obj->len + 1) * sizeof(jval *));
  obj->keys[obj->len] = (char *)malloc(strlen(key) + 1);
  strcpy(obj->keys[obj->len], key);
  obj->items[obj->len] = val;
  obj->len++;
}

static jval *jv_get(jval *obj, const char *key) {
  size_t i;
  if (!obj || obj->type != 5) return NULL;
  for (i = 0; i < obj->len; i++) {
    if (strcmp(obj->keys[i], key) == 0) return obj->items[i];
  }
  return NULL;
}

static const char *jv_skip_ws(const char *p) {
  while (*p == ' ' || *p == '\t' || *p == '\n' || *p == '\r') p++;
  return p;
}

static jval *jv_parse_value(const char **pp);

static jval *jv_parse_string(const char **pp) {
  const char *p = *pp;
  char buf[4096];
  size_t n = 0;
  if (*p != '"') return NULL;
  p++;
  while (*p && *p != '"') {
    if (*p == '\\' && p[1]) {
      p++;
      switch (*p) {
        case 'n': buf[n++] = '\n'; break;
        case 't': buf[n++] = '\t'; break;
        case 'r': buf[n++] = '\r'; break;
        case 'b': buf[n++] = '\b'; break;
        case 'f': buf[n++] = '\f'; break;
        default: buf[n++] = *p; break;
      }
      p++;
    } else {
      buf[n++] = *p++;
    }
    if (n >= sizeof(buf) - 1) return NULL;
  }
  if (*p != '"') return NULL;
  buf[n] = 0;
  *pp = p + 1;
  return jv_str_new(buf);
}

static jval *jv_parse_number(const char **pp) {
  const char *p = *pp;
  char *end = NULL;
  double d = strtod(p, &end);
  if (end == p) return NULL;
  *pp = end;
  jval *v = jv_alloc(2);
  v->num = d;
  return v;
}

static jval *jv_parse_array(const char **pp) {
  const char *p = jv_skip_ws(*pp);
  jval *arr = jv_alloc(4);
  if (*p != '[') { jv_free(arr); return NULL; }
  p++;
  p = jv_skip_ws(p);
  if (*p == ']') { *pp = p + 1; return arr; }
  for (;;) {
    jval *item = jv_parse_value(&p);
    if (!item) { jv_free(arr); return NULL; }
    jv_push(arr, item);
    p = jv_skip_ws(p);
    if (*p == ',') { p++; continue; }
    if (*p == ']') { *pp = p + 1; return arr; }
    jv_free(arr);
    return NULL;
  }
}

static jval *jv_parse_object(const char **pp) {
  const char *p = jv_skip_ws(*pp);
  jval *obj = jv_alloc(5);
  if (*p != '{') { jv_free(obj); return NULL; }
  p++;
  p = jv_skip_ws(p);
  if (*p == '}') { *pp = p + 1; return obj; }
  for (;;) {
    jval *k = jv_parse_string(&p);
    if (!k || k->type != 3) { jv_free(obj); jv_free(k); return NULL; }
    p = jv_skip_ws(p);
    if (*p != ':') { jv_free(obj); jv_free(k); return NULL; }
    p++;
    jval *val = jv_parse_value(&p);
    if (!val) { jv_free(obj); jv_free(k); return NULL; }
    jv_set(obj, k->str, val);
    jv_free(k);
    p = jv_skip_ws(p);
    if (*p == ',') { p++; continue; }
    if (*p == '}') { *pp = p + 1; return obj; }
    jv_free(obj);
    return NULL;
  }
}

static jval *jv_parse_value(const char **pp) {
  const char *p = jv_skip_ws(*pp);
  jval *v = NULL;
  if (*p == '"') v = jv_parse_string(&p);
  else if (*p == '[') v = jv_parse_array(&p);
  else if (*p == '{') v = jv_parse_object(&p);
  else if (*p == 't' && strncmp(p, "true", 4) == 0) { v = jv_alloc(1); v->boolean = 1; p += 4; }
  else if (*p == 'f' && strncmp(p, "false", 5) == 0) { v = jv_alloc(1); p += 5; }
  else if (*p == 'n' && strncmp(p, "null", 4) == 0) { v = jv_alloc(0); p += 4; }
  else v = jv_parse_number(&p);
  *pp = p;
  return v;
}

static jval *jv_parse(const char *s) {
  const char *p = s;
  jval *v = jv_parse_value(&p);
  if (!v) return NULL;
  p = jv_skip_ws(p);
  if (*p != 0) { jv_free(v); return NULL; }
  return v;
}

static void jv_serialize_into(jval *v, char **out, size_t *cap) {
  char tmp[64];
  size_t need;
  if (!v) return;
  if (*cap == 0) { *cap = 128; *out = (char *)malloc(*cap); if (!*out) return; (*out)[0] = 0; }
  switch (v->type) {
    case 0: need = 4; snprintf(tmp, sizeof(tmp), "null"); break;
    case 1: need = 5; snprintf(tmp, sizeof(tmp), v->boolean ? "true" : "false"); break;
    case 2: need = 32; snprintf(tmp, sizeof(tmp), "%.17g", v->num); break;
    case 3: need = strlen(v->str) + 2; break;
    case 4: need = 2; break;
    case 5: need = 2; break;
    default: return;
  }
  if (*cap < strlen(*out) + need + 2) {
    *cap = (*cap + need + 2) * 2;
    *out = (char *)realloc(*out, *cap);
  }
  if (v->type == 3) {
    strcat(*out, "\"");
    strcat(*out, v->str);
    strcat(*out, "\"");
  } else if (v->type == 4) {
    size_t i;
    strcat(*out, "[");
    for (i = 0; i < v->len; i++) {
      if (i) strcat(*out, ",");
      jv_serialize_into(v->items[i], out, cap);
    }
    strcat(*out, "]");
  } else if (v->type == 5) {
    size_t i;
    strcat(*out, "{");
    for (i = 0; i < v->len; i++) {
      if (i) strcat(*out, ",");
      strcat(*out, "\"");
      strcat(*out, v->keys[i]);
      strcat(*out, "\":");
      jv_serialize_into(v->items[i], out, cap);
    }
    strcat(*out, "}");
  } else {
    strcat(*out, tmp);
  }
}

static char *jv_serialize(jval *v) {
  char *out = NULL;
  size_t cap = 0;
  jv_serialize_into(v, &out, &cap);
  return out ? out : strdup("null");
}


static jval *jv_error(const char *msg) {
  jval *obj = jv_alloc(5);
  jval *okv = jv_alloc(1); okv->boolean = 0;
  jv_set(obj, "ok", okv);
  jv_set(obj, "error", jv_str_new(msg));
  return obj;
}

static jval *jv_bytes_new(const uint8_t *data, size_t len) {
  jval *arr = jv_alloc(4);
  size_t i;
  for (i = 0; i < len; i++) {
    jval *n = jv_alloc(2); n->num = (double)data[i];
    jv_push(arr, n);
  }
  return arr;
}

static jval *wrap_result(jval *result) {
  jval *obj = jv_alloc(5);
  jval *okv = jv_alloc(1); okv->boolean = 1;
  jv_set(obj, "ok", okv);
  jv_set(obj, "result", result);
  return obj;
}

// ====================================================================
// Your functions — edit the bodies below (signatures are generated)
// ====================================================================

static double fn_add(double a, double b) {
  // TODO: implement the body of add
  return 0.0;
}

// ====================================================================
// FFI boundary — DO NOT EDIT
// ====================================================================
static jval *dispatch(const char *name, jval *args) {
  if (strcmp(name, "add") == 0) {
  jval *_p_a = jv_get(args, "a");
  if (!_p_a || _p_a->type != 2)
    return jv_error("[add] param \"a\": expected number");
  double a = _p_a->num;
  jval *_p_b = jv_get(args, "b");
  if (!_p_b || _p_b->type != 2)
    return jv_error("[add] param \"b\": expected number");
  double b = _p_b->num;
  { jval *_r = jv_alloc(2); _r->num = fn_add(a, b); return wrap_result(_r); }
  }
  return jv_error("unknown native function");
}

__attribute__((visibility("default")))
char *asijs_call(const char *input) {
  jval *req = jv_parse(input);
  if (!req) return strdup("{\"ok\":false,\"error\":\"invalid JSON\"}");
  jval *namev = jv_get(req, "fn");
  jval *args = jv_get(req, "args");
  if (!namev || namev->type != 3 || !args) {
    jv_free(req);
    return strdup("{\"ok\":false,\"error\":\"missing fn/args\"}");
  }
  jval *resp = dispatch(namev->str, args);
  char *out = jv_serialize(resp);
  jv_free(resp);
  jv_free(req);
  return out;
}

__attribute__((visibility("default")))
void asijs_free(char *ptr) {
  free(ptr);
}
