// Auto-generated by AsiJS — DO NOT EDIT the FFI section below.
// Your code: fill in the bodies of the functions marked with TODO.
// Re-run "asi native scaffold go" to regenerate the FFI glue.
package main

/*
#include <stdlib.h>
*/
import "C"

import (
	"encoding/json"
	"fmt"
	"unsafe"
)

type asijsResponse struct {
	Ok     bool            `json:"ok"`
	Result json.RawMessage `json:"result,omitempty"`
	Error  string          `json:"error,omitempty"`
}

// ====================================================================
// Your functions — edit the bodies below (signatures are generated)
// ====================================================================

func add(a float64, b float64) float64 {
	// TODO: implement the body of add
	panic("implement add")
}

// ====================================================================
// FFI boundary — DO NOT EDIT
// ====================================================================
func dispatch(name string, args map[string]any) (any, error) {
	switch name {
		case "add":
	a, err := argNumber(args, "a", "add")
	if err != nil {
		return nil, err
	}
	b, err := argNumber(args, "b", "add")
	if err != nil {
		return nil, err
	}
	return add(a, b), nil
	default:
		return nil, fmt.Errorf("unknown native function: %s", name)
	}
}

//export asijs_call
func asijs_call(input *C.char) *C.char {
	var req struct {
		Fn   string         `json:"fn"`
		Args map[string]any `json:"args"`
	}
	if err := json.Unmarshal([]byte(C.GoString(input)), &req); err != nil {
		return cString(asijsResponse{Ok: false, Error: "invalid JSON: " + err.Error()})
	}
	result, err := dispatch(req.Fn, req.Args)
	if err != nil {
		return cString(asijsResponse{Ok: false, Error: err.Error()})
	}
	out, err := json.Marshal(result)
	if err != nil {
		return cString(asijsResponse{Ok: false, Error: "marshal error: " + err.Error()})
	}
	return cString(asijsResponse{Ok: true, Result: out})
}

//export asijs_free
func asijs_free(ptr *C.char) {
	C.free(unsafe.Pointer(ptr))
}

func cString(resp asijsResponse) *C.char {
	b, err := json.Marshal(resp)
	if err != nil {
		return C.CString(`{"ok":false,"error":"marshal error"}`)
	}
	return C.CString(string(b))
}

func argString(args map[string]any, key, fn string) (string, error) {
	v, ok := args[key]
	if !ok {
		return "", fmt.Errorf("[%s] param %q: missing", fn, key)
	}
	s, ok := v.(string)
	if !ok {
		return "", fmt.Errorf("[%s] param %q: expected string", fn, key)
	}
	return s, nil
}

func argNumber(args map[string]any, key, fn string) (float64, error) {
	v, ok := args[key]
	if !ok {
		return 0, fmt.Errorf("[%s] param %q: missing", fn, key)
	}
	n, ok := v.(float64)
	if !ok {
		return 0, fmt.Errorf("[%s] param %q: expected number", fn, key)
	}
	return n, nil
}

func argBool(args map[string]any, key, fn string) (bool, error) {
	v, ok := args[key]
	if !ok {
		return false, fmt.Errorf("[%s] param %q: missing", fn, key)
	}
	b, ok := v.(bool)
	if !ok {
		return false, fmt.Errorf("[%s] param %q: expected boolean", fn, key)
	}
	return b, nil
}

func argBytes(args map[string]any, key, fn string) ([]byte, error) {
	v, ok := args[key]
	if !ok {
		return nil, fmt.Errorf("[%s] param %q: missing", fn, key)
	}
	items, ok := v.([]any)
	if !ok {
		return nil, fmt.Errorf("[%s] param %q: expected byte array", fn, key)
	}
	out := make([]byte, len(items))
	for i, item := range items {
		n, ok := item.(float64)
		if !ok {
			return nil, fmt.Errorf("[%s] param %q: byte %d is not a number", fn, key, i)
		}
		out[i] = byte(n)
	}
	return out, nil
}

func argJSON(args map[string]any, key, fn string) (any, error) {
	v, ok := args[key]
	if !ok {
		return nil, fmt.Errorf("[%s] param %q: missing", fn, key)
	}
	return v, nil
}

func main() {}
