// Auto-generated by AsiJS — DO NOT EDIT the FFI section below.
// Your code: fill in the bodies of the functions marked with TODO.
// Re-run "asi native scaffold zig" to regenerate the FFI glue.
const std = @import("std");
const allocator = std.heap.c_allocator;

// ====================================================================
// Your functions — edit the bodies below (signatures are generated)
// ====================================================================

pub fn add(a: f64, b: f64) f64 {
    // TODO: implement the body of add
    return 0;
}

// ====================================================================
// FFI boundary — DO NOT EDIT
// ====================================================================
fn jvError(msg: []const u8) std.json.Value {
    var map = std.json.ObjectMap.init(allocator);
    map.put("ok", std.json.Value{ .bool = false }) catch {};
    map.put("error", std.json.Value{ .string = msg }) catch {};
    return std.json.Value{ .object = map };
}

fn dispatch(name: []const u8, args: std.json.ObjectMap) std.json.Value {
    if (std.mem.eql(u8, name, "add")) {
        const a: f64 = switch (args.get("a")) {
            .some => |v| switch (v) {
                .number => |n| n,
                .integer => |i| @floatFromInt(i),
                else => return jvError("[add] param \"a\": expected number"),
            },
            .none => return jvError("[add] param \"a\": missing"),
        };
        const b: f64 = switch (args.get("b")) {
            .some => |v| switch (v) {
                .number => |n| n,
                .integer => |i| @floatFromInt(i),
                else => return jvError("[add] param \"b\": expected number"),
            },
            .none => return jvError("[add] param \"b\": missing"),
        };
        return std.json.Value{ .object = blk: {
            var map = std.json.ObjectMap.init(allocator);
            const out = add(a, b);
            try map.put("ok", std.json.Value{ .bool = true });
            try map.put("result", std.json.Value{ .number = out });
            break :blk map;
        } };
    }
    return jvError("unknown native function");
}

export fn asijs_call(input: [*:0]const u8) ?[*:0]u8 {
    const parsed = std.json.parseFromSlice(std.json.Value, allocator, std.mem.span(input), .{}) catch
        return std.mem.dupeZ(u8, allocator, "{\"ok\":false,\"error\":\"invalid JSON\"}") catch null;
    defer parsed.deinit();
    const req = parsed.value;
    const name = if (req.object.get("fn")) |v| (v.string orelse return null) else return null;
    const args = if (req.object.get("args")) |v| v.object else return null;
    const resp = dispatch(name, args);
    var buf = std.ArrayList(u8).init(allocator);
    std.json.stringify(resp, .{}, buf.writer()) catch return null;
    return buf.toOwnedSliceSentinel(0) catch null;
}

export fn asijs_free(ptr: [*:0]u8) void {
    allocator.free(std.mem.span(ptr));
}
