/**
 * OpenAPI Client Codegen
 *
 * Generates a fully typed TypeScript fetch client from an OpenAPI 3.x document.
 *
 * Features:
 * - Path parameters (/:id → {id})
 * - Query parameters with required/optional
 * - Request body types
 * - Response types per status code
 * - Bearer token auth
 * - Custom base URL and fetch implementation
 *
 * @example
 * ```ts
 * import { generateClient, type OpenAPIClientConfig } from "asijs";
 *
 * // From an OpenAPI JSON spec URL:
 * const spec = await fetch("https://api.example.com/openapi.json").then(r => r.json());
 * const code = generateClient(spec, {
 *   clientName: "api",
 *   baseUrl: "https://api.example.com",
 * });
 * // → Generates a `api.ts` file with fully typed functions
 * ```
 */

export interface CodegenOptions {
  /** Name of the generated client class/namespace (default: "api") */
  clientName?: string;
  /** Default base URL (optional — can be set at runtime) */
  baseUrl?: string;
  /** Generate React Query / TanStack Query hooks (default: false) */
  reactQuery?: boolean;
  /** Generate Zod schemas instead of TypeScript interfaces (default: false) */
  zodSchemas?: boolean;
  /** Include JSDoc comments from spec description (default: true) */
  jsDoc?: boolean;
  /** Custom header for every request */
  defaultHeaders?: Record<string, string>;
}

/** Result of a codegen pass (generated code + applied transforms). */
export interface CodegenResult {
  code: string;
  clientName: string;
  operations: CodegenOperation[];
}

/** One operation being codegen'd (method, path, schema). */
export interface CodegenOperation {
  method: string;
  path: string;
  operationId: string;
  functionName: string;
  hasBody: boolean;
  hasParams: boolean;
  hasQuery: boolean;
  responseType: string;
}

/**
 * Generate a TypeScript client from an OpenAPI document.
 *
 * @param spec — OpenAPI 3.x document (parsed JSON)
 * @param options — CodegenOptions
 * @returns Generated TypeScript source code
 */
export function generateClient(
  spec: Record<string, unknown>,
  options: CodegenOptions = {},
): CodegenResult {
  const clientName = options.clientName ?? "api";
  const baseUrl = options.baseUrl ?? "";
  const genJsDoc = options.jsDoc ?? true;

  const lines: string[] = [];
  const operations: CodegenOperation[] = [];

  // ===== Header =====
  lines.push(`// Auto-generated by AsiJS OpenAPI Codegen — DO NOT EDIT`);
  const specInfo = spec.info as Record<string, unknown> | undefined;
  lines.push(`// Generated from: ${(specInfo?.title as string) ?? "OpenAPI"} ${(specInfo?.version as string) ?? ""}`);
  lines.push();
  lines.push(`type FetchFn = (url: string, init?: RequestInit) => Promise<Response>;`);
  lines.push();

  // ===== Client class =====
  if (baseUrl) {
    lines.push(`const DEFAULT_BASE_URL = ${JSON.stringify(baseUrl)};`);
    lines.push();
  }

  lines.push(`export interface ${clientName}Config {`);
  lines.push(`  baseUrl?: string;`);
  lines.push(`  fetch?: FetchFn;`);
  lines.push(`  headers?: Record<string, string>;`);
  if (hasAuth(spec)) {
    lines.push(`  token?: string | (() => string | Promise<string>);`);
  }
  lines.push(`}`);
  lines.push();

  // Response types
  lines.push(`export interface ${clientName}Response<T> {`);
  lines.push(`  data: T;`);
  lines.push(`  status: number;`);
  lines.push(`  headers: Headers;`);
  lines.push(`}`);
  lines.push();

  lines.push(`export class ${pascalCase(clientName)}Client {`);
  lines.push(`  private baseUrl: string;`);
  lines.push(`  private fetchFn: FetchFn;`);
  lines.push(`  private headers: Record<string, string>;`);
  if (hasAuth(spec)) {
    lines.push(`  private token?: string | (() => string | Promise<string>);`);
  }
  lines.push();
  lines.push(`  constructor(config: ${clientName}Config = {}) {`);
  lines.push(`    this.baseUrl = config.baseUrl ?? ${baseUrl ? "DEFAULT_BASE_URL" : '""'};`);
  lines.push(`    this.fetchFn = config.fetch ?? globalThis.fetch.bind(globalThis);`);
  lines.push(`    this.headers = { ...config.headers };`);
  if (hasAuth(spec)) {
    lines.push(`    this.token = config.token;`);
  }
  lines.push(`  }`);
  lines.push();

  // Setter for token
  if (hasAuth(spec)) {
    lines.push(`  setToken(token: string | (() => string | Promise<string>)): void {`);
    lines.push(`    this.token = token;`);
    lines.push(`  }`);
    lines.push();
  }

  // Private request method
  lines.push(`  private async request<T>(`);
  lines.push(`    method: string,`);
  lines.push(`    path: string,`);
  lines.push(`    params?: Record<string, string>,`);
  lines.push(`    query?: Record<string, string | string[] | undefined>,`);
  lines.push(`    body?: unknown,`);
  lines.push(`  ): Promise<${clientName}Response<T>> {`);
  lines.push(`    let url = \`\${this.baseUrl}\${path}\`;`);
  lines.push();
  lines.push(`    // Replace path parameters`);
  lines.push(`    if (params) {`);
  lines.push(`      for (const [key, value] of Object.entries(params)) {`);
  lines.push(`        url = url.replace(\`{\${key}}\`, encodeURIComponent(value));`);
  lines.push(`      }`);
  lines.push(`    }`);
  lines.push();
  lines.push(`    // Add query parameters`);
  lines.push(`    if (query) {`);
  lines.push(`      const qp = new URLSearchParams();`);
  lines.push(`      for (const [key, value] of Object.entries(query)) {`);
  lines.push(`        if (value === undefined) continue;`);
  lines.push(`        if (Array.isArray(value)) {`);
  lines.push(`          for (const v of value) qp.append(key, v);`);
  lines.push(`        } else {`);
  lines.push(`          qp.set(key, value);`);
  lines.push(`        }`);
  lines.push(`      }`);
  lines.push(`      const qs = qp.toString();`);
  lines.push(`      if (qs) url += \`?\${qs}\`;`);
  lines.push(`    }`);
  lines.push();
  lines.push(`    const headers: Record<string, string> = {`);
  lines.push(`      ...this.headers,`);
  lines.push(`    };`);
  lines.push();
  lines.push(`    if (body && !(body instanceof FormData)) {`);
  lines.push(`      headers["Content-Type"] = "application/json";`);
  lines.push(`    }`);
  if (hasAuth(spec)) {
    lines.push(`    if (this.token) {`);
    lines.push(`      const token = typeof this.token === "function"`);
    lines.push(`        ? await this.token()`);
    lines.push(`        : this.token;`);
    lines.push(`      headers["Authorization"] = \`Bearer \${token}\`;`);
    lines.push(`    }`);
  }
  lines.push();
  lines.push(`    const response = await this.fetchFn(url, {`);
  lines.push(`      method,`);
  lines.push(`      headers,`);
  lines.push(`      body: body instanceof FormData ? body : body ? JSON.stringify(body) : undefined,`);
  lines.push(`    });`);
  lines.push();
  lines.push(`    const data = response.status === 204`);
  lines.push(`      ? undefined`);
  lines.push(`      : await response.json();`);
  lines.push();
  lines.push(`    return {`);
  lines.push(`      data: data as T,`);
  lines.push(`      status: response.status,`);
  lines.push(`      headers: response.headers,`);
  lines.push(`    };`);
  lines.push(`  }`);
  lines.push();

  // ===== Generate operations =====
  const paths = spec.paths as Record<string, Record<string, Record<string, unknown>>> | undefined;
  if (paths) {
    for (const [path, methods] of Object.entries(paths)) {
      for (const [method, operation] of Object.entries(methods)) {
        if (!["get", "post", "put", "delete", "patch", "head", "options"].includes(method)) continue;
        const op = generateOperation(path, method, operation, clientName, genJsDoc, spec);
        lines.push(...op.lines);
        operations.push(op.meta);
      }
    }
  }

  // Close class
  lines.push(`}`);
  lines.push();

  // ===== Default export instance =====
  if (baseUrl) {
    lines.push(`export const ${clientName} = new ${pascalCase(clientName)}Client();`);
    lines.push();
  }

  // ===== Type aliases for responses =====
  lines.push(`// ===== Response type helpers =====`);
  lines.push(`type ApiResponse<T> = ${clientName}Response<T>;`);
  lines.push();

  const code = lines.join("\n");
  return { code, clientName, operations };
}

interface OperationLines {
  lines: string[];
  meta: CodegenOperation;
}

function generateOperation(
  path: string,
  method: string,
  operation: Record<string, unknown>,
  clientName: string,
  genJsDoc: boolean,
  _spec: Record<string, unknown>,
): OperationLines {
  const operationId = (operation.operationId as string) || `${method}${path.replace(/[\/{}:]/g, "_")}`;
  const functionName = camelCase(operationId);
  const description = operation.description as string || operation.summary as string || "";

  const pathParams = extractPathParams(path);
  const queryParams = extractQueryParams(operation);
  const bodySchema = extractBodySchema(operation);
  const responseTypes = extractResponseTypes(operation);

  // Build TypeScript type for response
  const responseType = responseTypes["200"] ?? responseTypes["201"] ?? "unknown";
  const hasParams = pathParams.length > 0;
  const hasQuery = queryParams.length > 0;
  const hasBody = bodySchema !== null;

  const lines: string[] = [];

  // JSDoc
  if (genJsDoc && description) {
    lines.push(`  /**`);
    lines.push(`   * ${description.replace(/\n/g, "\n   * ")}`);
    lines.push(`   */`);
  }

  // Method signature
  const paramParts: string[] = [];
  if (hasParams) {
    const props = pathParams.map((p) => `${p}: string`).join("; ");
    paramParts.push(`params: { ${props} }`);
  }
  if (hasQuery) {
    const props = queryParams
      .map((q) => `${q.name}${q.required ? "" : "?"}: ${q.type}`)
      .join("; ");
    paramParts.push(`query: { ${props} }`);
  }
  if (hasBody) {
    paramParts.push(`body: ${bodySchema}`);
  }

  const signature = paramParts.length > 0 ? `({ ${paramParts.join(", ") } }: { ${paramParts.map((p) => p).join("; ")} })` : "()";
  const callArgs: string[] = [];

  const openApiPath = path.replace(/:([^/]+)/g, "{$1}");
  callArgs.push(JSON.stringify(method.toUpperCase()));
  callArgs.push(JSON.stringify(openApiPath));
  callArgs.push(hasParams ? "params" : "undefined");
  callArgs.push(hasQuery ? "query" : "undefined");
  callArgs.push(hasBody ? "body" : "undefined");

  lines.push(`  async ${functionName}${signature}: Promise<${clientName}Response<${responseType}>> {`);
  lines.push(`    return this.request<${responseType}>(${callArgs.join(", ")});`);
  lines.push(`  }`);
  lines.push();

  return {
    lines,
    meta: {
      method: method.toUpperCase(),
      path,
      operationId,
      functionName,
      hasBody,
      hasParams,
      hasQuery,
      responseType: responseType as string,
    },
  };
}

// ============================================================================
// Helper functions
// ============================================================================

function extractPathParams(path: string): string[] {
  const params: string[] = [];
  const regex = /{([^}]+)}/g;
  let match: RegExpExecArray | null;
  while ((match = regex.exec(path)) !== null) {
    params.push(match[1]);
  }
  return params;
}

function extractQueryParams(operation: Record<string, unknown>): Array<{ name: string; required: boolean; type: string }> {
  const params: Array<{ name: string; required: boolean; type: string }> = [];
  const parameters = operation.parameters as Array<Record<string, unknown>> | undefined;
  if (!parameters) return params;

  for (const param of parameters) {
    if (param.in !== "query") continue;
    const name = param.name as string;
    const required = param.required === true;
    const schema = param.schema as Record<string, unknown> | undefined;
    const type = schemaToType(schema);
    params.push({ name, required, type: type as string });
  }
  return params;
}

function extractBodySchema(operation: Record<string, unknown>): string | null {
  const requestBody = operation.requestBody as Record<string, unknown> | undefined;
  if (!requestBody) return null;

  const content = requestBody.content as Record<string, { schema?: Record<string, unknown> }> | undefined;
  if (!content) return null;

  const jsonContent = content["application/json"];
  if (!jsonContent?.schema) return null;

  return schemaToTypeString(jsonContent.schema);
}

function extractResponseTypes(operation: Record<string, unknown>): Record<string, string> {
  const types: Record<string, string> = {};
  const responses = operation.responses as Record<string, Record<string, unknown>> | undefined;
  if (!responses) return types;

  for (const [status, response] of Object.entries(responses)) {
    const content = response.content as Record<string, { schema?: Record<string, unknown> }> | undefined;
    if (!content?.["application/json"]?.schema) {
      types[status] = "undefined";
      continue;
    }
    types[status] = schemaToTypeString(content["application/json"].schema);
  }

  return types;
}

function schemaToTypeString(schema: Record<string, unknown>): string {
  const ref = schema.$ref as string | undefined;
  if (ref) {
    const parts = ref.split("/");
    return parts[parts.length - 1]!;
  }

  if (schema.allOf) {
    const items = schema.allOf as Record<string, unknown>[];
    return items.map((s) => schemaToTypeString(s)).join(" & ");
  }
  if (schema.oneOf) {
    const items = schema.oneOf as Record<string, unknown>[];
    return items.map((s) => schemaToTypeString(s)).join(" | ");
  }
  if (schema.anyOf) {
    const items = schema.anyOf as Record<string, unknown>[];
    return items.map((s) => schemaToTypeString(s)).join(" | ");
  }

  const type = schema.type as string | undefined;
  const properties = schema.properties as Record<string, unknown> | undefined;
  const items = schema.items as Record<string, unknown> | undefined;
  const enumValues = schema.enum as string[] | undefined;

  if (enumValues) {
    return enumValues.map((v) => JSON.stringify(v)).join(" | ");
  }

  if (type === "object" && properties) {
    const required = new Set<string>((schema.required as string[]) ?? []);
    const props = Object.entries(properties).map(([name, prop]) => {
      const optional = !required.has(name) ? "?" : "";
      return `${name}${optional}: ${schemaToTypeString(prop as Record<string, unknown>)}`;
    });
    return `{ ${props.join("; ")} }`;
  }

  if (type === "array" && items) {
    return `${schemaToTypeString(items)}[]`;
  }

  return schemaToType(schema);
}

function schemaToType(schema?: Record<string, unknown>): string {
  if (!schema) return "unknown";
  const type = schema.type as string | undefined;
  const isNullable = schema.nullable === true;

  const base = typeMap[type ?? "string"] ?? "unknown";
  return isNullable ? `${base} | null` : base;
}

const typeMap: Record<string, string> = {
  string: "string",
  number: "number",
  integer: "number",
  boolean: "boolean",
  object: "Record<string, unknown>",
  array: "unknown[]",
  null: "null",
};

function pascalCase(s: string): string {
  return s.replace(/(?:^|[-_./])(\w)/g, (_, c) => c.toUpperCase());
}

function camelCase(s: string): string {
  s = s.replace(/[-_./]/g, " ");
  return s.replace(/(?:^\w|[A-Z]|\b\w|\s+)/g, (match, index) =>
    index === 0 ? match.toLowerCase() : match.toUpperCase(),
  ).replace(/\s+/g, "");
}

function hasAuth(spec: Record<string, unknown>): boolean {
  const components = spec.components as Record<string, unknown> | undefined;
  const securitySchemes = components?.securitySchemes as Record<string, Record<string, unknown>> | undefined;
  if (!securitySchemes) return false;
  return Object.values(securitySchemes).some((s) =>
    s.scheme === "bearer" || s.type === "http" || s.type === "apiKey"
  );
}
